name: gotify

services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    ports:
      - 8080:8080
    environment:
      GOTIFY_SERVER_PORT: 8080
    volumes:
      - ./data:/app/data

  caddy:
    image: caddy:2.9.1-alpine
    container_name: gotify-proxy
    restart: unless-stopped
    ports:
      - 3003:3003
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./client.crt:/client.crt
